sudo: false
language: node_js
install: true
script: "./test/travis.sh"
env:
  matrix:
  - NODE=10
  - NODE=9
  - NODE=8
  - NODE=6
  - BROWSER=chrome
  - BROWSER=firefox
  - BROWSER=safari
  - BROWSER=iphone
  global:
  - secure: uEhb2NzD0u7rewj0wMoP/iSzqii0FfbmqHxBk8/HIYNizLAcw1NzxZu6aqhbdNfPtmMXNNzqglnthKIz/Rboaqtrv0rwgBbZqbtnS1AtXickdIIbjvR1TmnlkaKeESTahsSZdB22NoxLEyJ9GTaBXKoHdw24CyK/667G7v+aUpOmHlUw1Q0i6dBDaVG+GrQLM01vxTLokAabqb/vMOai0yK6xoh/K+psPKiWWhprEBmmdSRul6JICSkd8p1GAp4sMsBDD+Y/vAJYKsaPFuk+A4uYr6rZPWyXd1ApUGHkFLS0uwaB12WnJMR71OJ8m/B9vimu4U6y8Z7VK3hVmQjDJUpwxfRIxLOsCZ3r1hcNwMWh4zqYMLNM1gqPKV31NSrfuGES+cS9KY5DLDfSKQRzbnrFJRDssi9gCRcOrK7dSrGGAyKSNCWodr27YGTDFyoORHszHd8B+/5WoPz91LfmQeHXMN6sBTcU9y5+yPg6IC8f4dfGbppM404PJyILYq94LKVmKyLPWDOem+OSJWrBCJNdHlqvC4jdzUYG3Rcn1YEEcDlBuEa5K1E0dq2CJVzLN0URbT+mmyCxbbIEd5RYqWurC7uqVfJt4HLvfMdIfTidThyL6EMi5FiUGGN53oCEN2zEA+Ou7COjSEhnZkQWRv2/2H9d3xzom3gJpq8Wr6M=
  - secure: sQct9CyeNU9bnzQEpIMyatvfysQUgT4vFQ7nVemBdZOdbzGDq25Hx8VJmJDOHev5+Fz1ge9y3X5H+9DeS9JjV6sKirpG/ZhMKcsQNTGHypYwJ+ptZEdppdDLQg5elK29BbLqSspyt6cRq1GZ2X9+d8rOJJNbDG8P9a63UZQxsDpGVBEp7Do7IWNVfjjlwJiPCAtsqN+07hXHW6bdED36+/Zx5/Uq4WABnWsRfKN9q3YoiC4NYA0XMYHju8AN3ng2OYD20H5fb7+5lQIIZKeCeIlUDtoPPUVkOkQPCb0drVI4btRukN8KzSrB0IwQiV9q8yxCClO6Dfmly/hFIzTYWn0obkKT0Y6KlE4gFckhs+51+AISaWhQSWbyoQlWC8JJ1/50iNL2UuADu/r6BmKo9aF2b83JSbdnYraqVFNIm5njprvF+XD8YsywYHRhodNMRaw2cX06xK6fgVpAIGuF3YU62/99mbv71fhVVzHqnr7/+ksZVaaqgyjXlpDOKmH+TgJP2i2FJf3OH6z/b6SGXDoTyFacR4mjCm/FoPYeEX2rbo47ztXLvThUP6gnEbEDLC7zb3MAzIO1la2pbcFabK7fCHSdNfKA6B4vZphlBUqAblqqcxoZUbOpXrsYnEr+Jo7PZHI4eEtFb1/RkG/NapNrrJmHNi4oRfxT5TISaWg=
notifications:
  email: false
addons:
  sauce_connect: true
  hosts:
  - airtap.local
before_install: if [ -z "$BROWSER" ]; then unset SAUCE_USERNAME && unset SAUCE_ACCESS_KEY;
  fi
